server:
  port: 10000

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: true
  mvc:
    servlet:
      load-on-startup: 100

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.jnu.gulimall.product.dao: debug

feign:
  httpclient:
    connection-timeout: 5000