server:
  port: 13000

spring:
  cloud:
    alicloud:
      access-key: LTAI5tSkvhNmJF4h5qbZqBsF
      secret-key: lgHjabatTWp0T2WfchecLv1bBXqaq6
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:templates/,classpath:static/

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      key-prefix: CACHE_

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.jnu.gulimall: debug
