server:
  port: 20000
  servlet:
    session:
      timeout: 30m

spring:
  thymeleaf:
    cache: false
  redis:
    host: 110.40.220.85
    port: 6379
    password: 48691412
  session:
    store-type: redis
