server:
  port: 20000
  servlet:
    session:
      timeout: 30m


spring:
  thymeleaf:
    cache: false
  session:
    store-type: redis

feign:
  client:
    config:
      default:
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间,
        ConnectTimeOut: 5000
        #指建立连接后从服务端读取到可用资源所用的时间,默认为1s
        ReadTimeOut: 5000
